version: '3'
services:
  drupal:
    image: drupal
    ports:
      - "8080:80"
    volumes:
      - ./drupal:/var/www/html
    environment:
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
      - MYSQL_HOST=db
  db:
    image: mysql
    environment:
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
      - MYSQL_ROOT_PASSWORD=root

