version: '3.8'

services:
  drupal:
    image: drupal:10-apache
    ports:
      - '8080:80'
    volumes:
      - ./web:/var/www/html
    depends_on:
      - mysql
    environment:
      DRUPAL_DATABASE_HOST: mysql
      DRUPAL_DATABASE_PORT: 3306
      DRUPAL_DATABASE_NAME: drupal
      DRUPAL_DATABASE_USER: drupal
      DRUPAL_DATABASE_PASSWORD: drupal

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
